In [1]:
#--------------------------------
## IMPORTS
#--------------------------------
import sys
import os

# set the path to find the modules
#sys.path.insert(0, '../src/') #use relative path
os.chdir("../005_src")

from config import *

----------------------------------------
Packages import successful
Variables import successful
Helper Functions import successful
Functions import successful
Functions xml import successful
Functions graph import successful
Functions GCN import successful
Functions Plotting import successful
Functions Data Adjustments import successful
----------------------------------------
root directory: /storage/remote/atcremers50/ss21_multiagentcontrol/
input directory: /storage/remote/atcremers50/ss21_multiagentcontrol/004_data/
output directory: /storage/remote/atcremers50/ss21_multiagentcontrol/006_model_output/
----------------------------------------

----------------------------------------
root directory: /storage/remote/atcremers50/ss21_multiagentcontrol/
input directory: /storage/remote/atcremers50/ss21_multiagentcontrol/004_data/
output directory: /storage/remote/atcremers50/ss21_multiagentcontrol/006_model_output/
----------------------------------------

In [4]:
file_name = "20210703-17h59m26s_timesteps199_ec3500_em7000"
df_full, dfselected = select_rows_from_data(file_name,drop_col = True)
## TODO: remember to cast to tensors !!!

In [5]:
df_input_GCN

,data_x,data_pos,data_edges,data_y,data_edges_attr,training_row
5,"[[180.0, 7.17, 2.0], [180.0, 0.0, 3.0]]","[[92.0, 180.42], [92.0, 194.9]]","[[0], [1]]","[[92.0, 159.95, 180.0], [92.0, 189.29, 180.0]]",[1.1],True
6,"[[180.0, 9.33, 2.0], [180.0, 1.92, 3.0]]","[[92.0, 171.09], [92.0, 192.98]]","[[0], [1]]","[[92.0, 147.3, 180.0], [92.0, 183.45, 180.0]]",[1.1],True
7,"[[180.0, 11.14, 2.0], [180.0, 3.69, 3.0]]","[[92.0, 159.95], [92.0, 189.29]]","[[0], [1]]","[[92.0, 132.79, 180.0], [92.0, 175.71, 180.0]]",[1.1],True
8,"[[180.0, 12.65, 2.0], [180.0, 5.84, 3.0]]","[[92.0, 147.3], [92.0, 183.45]]","[[0], [1]]","[[92.0, 117.4, 180.0], [92.0, 166.63, 180.0]]",[1.2],True
9,"[[180.0, 14.52, 2.0], [180.0, 7.74, 3.0]]","[[92.0, 132.79], [92.0, 175.71]]","[[0], [1]]","[[93.17, 106.62, 170.48], [92.0, 155.81, 180.0]]",[1.3],True
...,...,...,...,...,...,...
194,"[[180.0, 0.0, 3.0], [90.0, 0.0, 3.0], [180.0, ...","[[92.0, 114.6], [70.4, 98.4], [95.2, 114.6], [...","[[30, 33, 35, 32, 34, 29, 32, 30, 36, 30, 30, ...","[[92.0, 114.6, 180.0], [70.4, 98.4, 90.0], [95...","[4.5, 3.4, 2.7, 5.9, 2.7, 2.7, 2.7, 4.5, 3.0, ...",True
195,"[[180.0, 0.0, 3.0], [90.0, 0.0, 3.0], [180.0, ...","[[92.0, 114.6], [70.4, 98.4], [95.2, 114.6], [...","[[30, 33, 35, 32, 34, 29, 32, 30, 36, 30, 30, ...","[[92.0, 114.6, 180.0], [71.71, 98.4, 90.0], [9...","[4.5, 3.4, 2.7, 6.0, 2.7, 2.7, 2.7, 4.5, 3.8, ...",True
196,"[[180.0, 0.0, 3.0], [90.0, 0.0, 3.0], [180.0, ...","[[92.0, 114.6], [70.4, 98.4], [95.2, 114.6], [...","[[30, 33, 35, 32, 34, 29, 32, 30, 36, 30, 30, ...","[[92.0, 114.6, 180.0], [74.86, 98.4, 90.0], [9...","[4.9, 3.4, 2.7, 6.0, 2.7, 2.7, 2.7, 4.9, 5.6, ...",True
197,"[[180.0, 0.0, 3.0], [90.0, 1.32, 3.0], [180.0,...","[[92.0, 114.6], [71.71, 98.4], [95.2, 114.6], ...","[[30, 33, 35, 32, 34, 29, 32, 30, 36, 30, 30, ...","[[92.0, 114.6, 180.0], [77.71, 98.4, 90.0], [9...","[5.9, 3.5, 2.7, 6.0, 2.7, 2.7, 2.7, 5.9, 6.0, ...",True
198,"[[180.0, 0.0, 3.0], [90.0, 3.15, 3.0], [180.0,...","[[92.0, 114.6], [74.86, 98.4], [95.2, 114.6], ...","[[30, 33, 35, 32, 34, 29, 32, 30, 36, 30, 30, ...","[[92.0, 114.6, 180.0], [80.6, 98.4, 90.0], [95...","[6.0, 4.0, 2.7, 6.0, 2.7, 2.7, 2.7, 6.5, 6.0, ...",True

In [3]:
file_name = "20210704-13h44m33s_timesteps200_ec3500_em7000"
df_input_GCN = select_rows_from_data(file_name,drop_col = True)
df_input_GCN

,data_x,data_pos,data_edges,data_edges_renamed,data_y,data_edges_attr,training_row
6,"[[180.0, 13.06, 2.0], [180.0, 0.0, 3.0]]","[[92.0, 146.78], [92.0, 194.9]]","[[0], [1]]","[[0], [1]]","[[92.0, 116.36, 180.0], [92.0, 190.01, 180.0]]",[1.1],True
7,"[[180.0, 14.83, 2.0], [180.0, 1.51, 3.0]]","[[92.0, 131.95], [92.0, 193.39]]","[[0], [1]]","[[0], [1]]","[[93.45, 105.41, 169.65], [92.0, 184.69, 180.0]]",[1.1],True
8,"[[180.0, 15.59, 2.0], [180.0, 3.38, 3.0]]","[[92.0, 116.36], [92.0, 190.01]]","[[0], [1]]","[[0], [1]]","[[100.81, 98.06, 123.47], [92.0, 178.04, 180.0]]",[1.1],True
9,"[[169.65, 11.09, 2.0], [180.0, 5.32, 3.0]]","[[93.45, 105.41], [92.0, 184.69]]","[[0], [1]]","[[0], [1]]","[[111.78, 95.42, 96.94], [92.0, 169.46, 180.0]]",[1.2],True
10,"[[123.47, 10.7, 2.0], [180.0, 6.65, 3.0]]","[[100.81, 98.06], [92.0, 178.04]]","[[0], [1]]","[[0], [1]]","[[122.58, 95.2, 90.0], [92.0, 159.14, 180.0]]",[1.3],True
...,...,...,...,...,...,...,...
193,"[[90.0, 0.0, 1.0], [90.0, 0.0, 0.0], [0.0, 0.0...","[[85.4, 92.0], [85.4, 98.4], [108.0, 85.4], [9...","[[16, 26, 23, 25, 16, 23, 16, 25, 23, 20, 27, ...","[[0, 5, 2, 4, 0, 2, 0, 4, 2, 1, 6, 0, 0, 1, 2,...","[[86.9, 92.0, 90.0], [86.72, 98.61, 87.51], [1...","[4.3, 2.6, 4.3, 3.3, 1.1, 1.1, 3.3, 4.3, 3.3, ...",True
194,"[[90.0, 0.0, 1.0], [90.0, 0.0, 0.0], [0.0, 0.0...","[[85.4, 92.0], [85.4, 98.4], [108.0, 85.4], [9...","[[16, 26, 23, 25, 16, 23, 16, 25, 23, 20, 27, ...","[[0, 5, 2, 4, 0, 2, 0, 4, 2, 1, 6, 0, 0, 1, 2,...","[[90.05, 92.0, 90.0], [87.5, 100.87, 47.91], [...","[4.3, 3.3, 4.3, 3.3, 1.1, 1.1, 3.3, 3.8, 3.3, ...",True
195,"[[90.0, 1.5, 1.0], [87.51, 1.39, 0.0], [0.0, 0...","[[86.9, 92.0], [86.72, 98.61], [108.0, 85.4], ...","[[16, 26, 23, 25, 16, 23, 16, 25, 23, 20, 27, ...","[[0, 5, 2, 4, 0, 2, 0, 4, 2, 1, 6, 0, 0, 1, 2,...","[[95.56, 92.0, 90.0], [84.21, 101.6, 299.37], ...","[4.3, 3.3, 4.3, 3.3, 1.1, 1.1, 3.3, 2.7, 3.3, ...",True
196,"[[90.0, 3.16, 1.0], [47.91, 2.97, 0.0], [0.0, ...","[[90.05, 92.0], [87.5, 100.87], [108.0, 85.4],...","[[16, 26, 23, 25, 16, 23, 16, 25, 23, 20, 27, ...","[[0, 5, 2, 4, 0, 2, 0, 4, 2, 1, 6, 0, 0, 1, 2,...","[[103.64, 92.0, 90.0], [78.17, 101.6, 270.0], ...","[4.3, 3.3, 4.3, 3.3, 1.2, 1.2, 3.3, 2.0, 3.3, ...",True
197,"[[90.0, 5.53, 1.0], [299.37, 3.51, 0.0], [0.0,...","[[95.56, 92.0], [84.21, 101.6], [108.0, 85.4],...","[[16, 26, 23, 25, 16, 23, 16, 25, 23, 20, 27, ...","[[0, 5, 2, 4, 0, 2, 0, 4, 2, 1, 6, 0, 0, 1, 2,...","[[114.15, 92.0, 90.0], [70.51, 101.6, 270.0], ...","[4.3, 3.3, 4.3, 3.3, 1.3, 1.3, 3.3, 1.6, 3.3, ...",True